name: React basic demo

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}--whatever--${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
          restore-key: |
            ${{ runner.os }}--whatever--
            ${{ runner.os }}--    



      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm test        
          
      - name: Linting
        run: npm run lint

      - name: Building
        run: npm run build
        
      - name: Deploying to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to s3 bucket
        run: aws s3 sync ./build s3://react-s3-cicd-githup-actions


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ammarfad /react-cicd:latest

      

